### ISSUE TITLE
Refactor V3 parser: split parsing logic on multiple files

### ISSUE THREAD

**Issue by alexprey** [alexprey/sveltedoc-parser#53]
Currently the most logic of svelte component parsing contains at the one file.
As a minimum plan for refactoring is: split markup and script parsing logic to different files.

**Comment by soft-decay** [comment]
Hi @alexprey, I'd like to work on this.

This is the general refactoring plan I have in mind:
- Move `parseTemplate` in a separate file as a TemplateParser
- Move `parseScript` in a separate file as a ScriptParser
- TemplateParser and ScriptParser would receive a reference to Svelte3Parser in the constructor to access internal options, identifiers, etc.
- Rename the v3 parser to Svelte3Parser
- Have Svelte3Parser subscribe to events of TemplateParser and ScriptParser (both extends EventEmitter) in this way:
> ```
>                         <-- TemplateParser
> parse <-- Svelte3Parser 
>                         <-- ScriptParser
> ```
- Extract some methods of Svelte3Parser as utility functions (a lot of them don't have references to `this` so it should be simple) :
  - parseVariableDeclaration
  - parseFunctionDeclaration
  - parseObjectProperty
  - parseKeywords

Anything else you had in mind or things to be careful about?

**Comment by alexprey** [comment]
Hi, ok, I'm assign you for this task. Not sure that I'm completelly understand what you want to do. At the first looks it should be ok, but I need to mention that you should keep in mind the following:

- Script parser must can handle 2 types of scripts:
-- Module

**Comment by soft-decay** [comment]
The refactoring is going pretty well so far. Came across this constant:

```js
const SCOPE_MARKUP = 'markup';
```

Which  is used as a condition (`parseContext.scopeType !== SCOPE_MARKUP`) in `parseBodyRecursively`.

Problem is that scopeType is never set to `SCOPE_MARKUP`, instead in `parseMarkupExpressionBlock`:

```js
const scriptParseContext = {
  scope: SCOPE_MARKUP,
  offset: offset,
  sourceCode: sourceCode
};
```
 
Should I attempt to remove this conditional check which seems useless?
(all tests pass with `scopeType === undefined` and with `scopeType === "SCOPE_MARKUP"`)

**Comment by alexprey** [comment]
Heh, that looks like a mistake :) Of course it should `scopeType`. I'm recheck conditions with this constant and it used for additional syntax check and prevent variable declarations and another things for expressions, like: `<button on:click={() => { import AComponent from './AComponent'; }}>`. But actually, this case is really rarity, so I it because now it works fine, but anyway scope must be specified correcly.

Please keep this constant and checks and fix the setting of this property at `parseMarkupExpressionBlock` method. Thanks for the finding!

**Comment by soft-decay** [comment]
I created a draft PR #56 for this issue (there is also a brief description in the PR).

I'm not sure what I should do next.

Most of the logic has been split, but the `parseBodyRecursively` method is still really monolithic. Should I try to make it more readable by splitting it different parts, or is it out of scope?

**Comment by soft-decay** [comment]
I found a bug while refactoring. The code handling _exported_ variable declarations is not the same as the code handling variable declarations (it's mostly duplicated). (If you're interested the code for non-exported is [here](https://github.com/soft-decay/sveltedoc-parser/blob/5e20900d38a6f8b72c9ddf57ba63a7e85c6d789a/lib/v3/script.js#L188) and for exported is [here](https://github.com/soft-decay/sveltedoc-parser/blob/5e20900d38a6f8b72c9ddf57ba63a7e85c6d789a/lib/v3/script.js#L245).

The differences are:
- emit 'private' vs 'public'
- comment absent vs present

I confirmed this by adding a test for _exported_ event parsing with identifiers and It failed (because identifiers were only added for the non-_exported_ variables). I can fix this with the refactoring (and also remove the code duplication), but I could also make a separate issue if you prefer.

**Comment by alexprey** [comment]
Ok, I think it is ok if you can reduce code duplications. Not completlly understand about what you found. Can you create issue with that and provide test file with reproducing that?

**Comment by alexprey** [comment]
About differences in parsing.
- `private` and `public` that is correct. By default, only exported items must be public.
- comment parsed anyway in for exported and non-exported variables. But for exported items it should be implemented by another way. The common logic for parse comment are placed at `parseVariableDeclaration(...)` function. This function use `VariableDeclaration` ast node for both types. However, when variable are exported, the commen attaches to `ExportNamedDeclaration` node instead, so we need an extra logic to read comment.

**Comment by soft-decay** [comment]
Ok. I kept the comment from the `ExportNamedDeclaration` and passed it to the new method. The signature is:

```js
parseVariableDeclarations(declaration, context, level, visibility, comment = undefined);
```

so it handles both with and without a comment attached.

As for the bug, I fixed it in the [last commit](https://github.com/alexprey/sveltedoc-parser/pull/56/commits/232dcca46eceb695664311bfa2c15b12e32b217a) of the refactoring branch and I left some comments. I tested it by modifying an existing test.

**Comment by soft-decay** [comment]
Hi @alexprey,

I was wondering if you checked my PR at all. I left it as a draft because I don't know if I should go beyond what I already did.

I did not refactor `parseBodyRecursively` in depth because it has a lot of interactions/coupling and it would be a full refactoring endeavor in itself (maybe another issue later?).

Anyway, PR is ready for a first review (even though it's in draft) when you have some time.

Thanks.

**Comment by alexprey** [comment]
Hi @soft-decay I saw your PR on high level and mostly it liked by me. But I want to check it in deep, but still don't have enought time, sorry for that. I hope I can done with it on this week and we can merge it.

It's ok to keep the parseBody function, anyway it will planed to be rewrited for typescript

**Comment by alexprey** [comment]
Hi @soft-decay, I complete the review, and some improvements from my side. I'll add few comments in PR for some cases that I worred
